/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const RaceEntry = IDL.Record({
  'username' : IDL.Text,
  'character' : IDL.Text,
  'raceCompletionTime' : Time,
  'raceTrack' : IDL.Text,
  'runtime' : Time,
});

export const idlService = IDL.Service({
  'getRaceDetails' : IDL.Func([IDL.Text], [RaceEntry], ['query']),
  'getTrackLeaderboard' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
      ['query'],
    ),
  'getTracks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveRaceDetails' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, Time],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const RaceEntry = IDL.Record({
    'username' : IDL.Text,
    'character' : IDL.Text,
    'raceCompletionTime' : Time,
    'raceTrack' : IDL.Text,
    'runtime' : Time,
  });
  
  return IDL.Service({
    'getRaceDetails' : IDL.Func([IDL.Text], [RaceEntry], ['query']),
    'getTrackLeaderboard' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
        ['query'],
      ),
    'getTracks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveRaceDetails' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, Time],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };